service: wooblerapi
provider:
  name: aws
  runtime: nodejs12.x
  profile: woobler
  region: us-east-1
  environment:
    tableName: ${self:custom.tableName}
    bucketName: ${self:custom.bucketName}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
        - dynamodb:*
      Resource: '*'

functions:
  getFact:
    handler: lambdas/endpoints/getFactHandler.handler
    events:
      - http:
          path: get-fact/{ID}
          method: GET
          cors: true
  getDbFact:
    handler: lambdas/endpoints/getDbFact.handler
    events:
      - http:
          path: get-db-fact/{ID}
          method: GET
          cors: true
  addDbFact:
    handler: lambdas/endpoints/addDbFact.handler
    events:
      - http:
          path: add-db-fact/{ID}
          method: POST
          cors: true
  createFile:
    handler: lambdas/endpoints/createFile.handler
    events:
      - http:
          path: create-file/{fileName}
          method: POST
          cors: true

plugins:
  - serverless-s3-sync
  - serverless-webpack

package:
  individually: true

custom:
  tableName: science-facts
  bucketName: woobler-api-bucket
  s3Sync:
    - bucketName: ${self:custom.bucketName}
      localDir: UploadData

resources:
  Resources:
    WooblerApiBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}
    MyDynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST